### Apresentação do Projeto

Proposta para a construção de uma aplicação que realiza análise de sentimento dos candidatos à presidência.

Instalação das Bibliotecas

In [1]:
pip install snscrape

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting snscrape
  Downloading snscrape-0.3.4-py3-none-any.whl (35 kB)
Requirement already satisfied: lxml in /usr/local/lib/python3.7/dist-packages (from snscrape) (4.2.6)
Requirement already satisfied: requests[socks] in /usr/local/lib/python3.7/dist-packages (from snscrape) (2.23.0)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.7/dist-packages (from snscrape) (4.6.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests[socks]->snscrape) (2022.6.15)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests[socks]->snscrape) (2.10)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests[socks]->snscrape) (1.24.3)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests[socks]->snscrape) (3.0.4)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /usr/local/lib/python3.7/dist-packages (from requests[socks]->snscrape) (1.7.1)
Installing collected packages: snscrape
Successfully installed snscrape-0.3.4

Importando as Bibliotecas

In [2]:
import snscrape.modules.twitter as sntwitter

#Manipulação de Dados
import pandas as pd

In [3]:
maximo_de_tweets = 50

### Lula

In [4]:
lista_de_tweets_lula = []

In [5]:
for i, tweet in enumerate(sntwitter.TwitterSearchScraper(['lula']).get_items()):
  if i > maximo_de_tweets:
    break
  lista_de_tweets_lula.append([tweet.date, tweet.id, tweet.content])

In [6]:
type(lista_de_tweets_lula)

list

In [7]:
dataframe_tweets_lula = pd.DataFrame(lista_de_tweets_lula, columns=['Data_Hora', 'IdTweet', 'Tweet'])

In [8]:
dataframe_tweets_lula.head()

,Data_Hora,IdTweet,Tweet
0,2022-07-30 23:16:51+00:00,1553520025637625856,"@LulaOficial Exatamente, a verdade contra a su..."
1,2022-07-30 23:16:51+00:00,1553520024891047943,@gleisi @LulaOficial @CamiloSantanaCE @elmanof...
2,2022-07-30 23:16:49+00:00,1553520017127374848,"O Manifesto do Direito via USP, com 500 mil as..."
3,2022-07-30 23:16:49+00:00,1553520014518620162,@DeputadoFederal @LulaOficial 22🇧🇷🇧🇷🇧🇷🇧🇷🇧🇷🇧🇷
4,2022-07-30 23:16:49+00:00,1553520014342381569,"@LulaOficial Analisando, o molusco não sai as ..."

In [9]:
dataframe_tweets_lula['Candidato'] = 'Lula'

In [10]:
dataframe_tweets_lula.head()

,Data_Hora,IdTweet,Tweet,Candidato
0,2022-07-30 23:16:51+00:00,1553520025637625856,"@LulaOficial Exatamente, a verdade contra a su...",Lula
1,2022-07-30 23:16:51+00:00,1553520024891047943,@gleisi @LulaOficial @CamiloSantanaCE @elmanof...,Lula
2,2022-07-30 23:16:49+00:00,1553520017127374848,"O Manifesto do Direito via USP, com 500 mil as...",Lula
3,2022-07-30 23:16:49+00:00,1553520014518620162,@DeputadoFederal @LulaOficial 22🇧🇷🇧🇷🇧🇷🇧🇷🇧🇷🇧🇷,Lula
4,2022-07-30 23:16:49+00:00,1553520014342381569,"@LulaOficial Analisando, o molusco não sai as ...",Lula

### Bolsonaro

In [11]:
lista_de_tweets_bolsonaro = []

In [12]:
for i, tweet in enumerate(sntwitter.TwitterSearchScraper(['bolsonaro']).get_items()):
  if i > maximo_de_tweets:
    break
  lista_de_tweets_bolsonaro.append([tweet.date, tweet.id, tweet.content])

In [13]:
dataframe_tweets_bolsonaro = pd.DataFrame(lista_de_tweets_bolsonaro, columns=['Data_Hora', 'IdTweet', 'Tweet'])

In [14]:
dataframe_tweets_bolsonaro.head()

,Data_Hora,IdTweet,Tweet
0,2022-07-30 23:16:53+00:00,1553520031551594498,@jairmearrependi É que o Moro e o Bolsonaro sã...
1,2022-07-30 23:16:52+00:00,1553520027378262019,@FlavioBolsonaro @jairbolsonaro @tarcisiogdf J...
2,2022-07-30 23:16:51+00:00,1553520022991130626,@ZeliaDuncan_ E que bom que o BOLSONARO é meu ...
3,2022-07-30 23:16:49+00:00,1553520017127374848,"O Manifesto do Direito via USP, com 500 mil as..."
4,2022-07-30 23:16:49+00:00,1553520014342381569,"@LulaOficial Analisando, o molusco não sai as ..."

In [15]:
dataframe_tweets_bolsonaro['Candidato'] = 'Bolsonaro'

In [16]:
dataframe_tweets_bolsonaro.head()

,Data_Hora,IdTweet,Tweet,Candidato
0,2022-07-30 23:16:53+00:00,1553520031551594498,@jairmearrependi É que o Moro e o Bolsonaro sã...,Bolsonaro
1,2022-07-30 23:16:52+00:00,1553520027378262019,@FlavioBolsonaro @jairbolsonaro @tarcisiogdf J...,Bolsonaro
2,2022-07-30 23:16:51+00:00,1553520022991130626,@ZeliaDuncan_ E que bom que o BOLSONARO é meu ...,Bolsonaro
3,2022-07-30 23:16:49+00:00,1553520017127374848,"O Manifesto do Direito via USP, com 500 mil as...",Bolsonaro
4,2022-07-30 23:16:49+00:00,1553520014342381569,"@LulaOficial Analisando, o molusco não sai as ...",Bolsonaro

#### Ciro Gomes

In [17]:
lista_de_tweets_ciro = []

In [18]:
for i, tweet in enumerate(sntwitter.TwitterSearchScraper(['ciro gomes']).get_items()):
  if i > maximo_de_tweets:
    break
  lista_de_tweets_ciro.append([tweet.date, tweet.id, tweet.content])

In [19]:
dataframe_tweets_ciro = pd.DataFrame(lista_de_tweets_ciro, columns=['Data_Hora', 'IdTweet', 'Tweet'])

In [20]:
dataframe_tweets_ciro.head()

,Data_Hora,IdTweet,Tweet
0,2022-07-30 23:16:51+00:00,1553520026346524674,@Omardeideais Saiu o DataToalha com a intenção...
1,2022-07-30 23:16:43+00:00,1553519990237810688,@cirogomes Teria não!😂😂😂
2,2022-07-30 23:16:36+00:00,1553519962915934208,@cirogomes 👏
3,2022-07-30 23:16:26+00:00,1553519920494829568,@nave1964 @cirogomes Que vagsbundo
4,2022-07-30 23:16:13+00:00,1553519864589217792,"@cirogomes Cirão, cai pra direita velho, lá é ..."

In [21]:
dataframe_tweets_ciro['Candidato'] = 'Ciro Gomes'

In [22]:
dataframe_tweets_ciro.head()

,Data_Hora,IdTweet,Tweet,Candidato
0,2022-07-30 23:16:51+00:00,1553520026346524674,@Omardeideais Saiu o DataToalha com a intenção...,Ciro Gomes
1,2022-07-30 23:16:43+00:00,1553519990237810688,@cirogomes Teria não!😂😂😂,Ciro Gomes
2,2022-07-30 23:16:36+00:00,1553519962915934208,@cirogomes 👏,Ciro Gomes
3,2022-07-30 23:16:26+00:00,1553519920494829568,@nave1964 @cirogomes Que vagsbundo,Ciro Gomes
4,2022-07-30 23:16:13+00:00,1553519864589217792,"@cirogomes Cirão, cai pra direita velho, lá é ...",Ciro Gomes

In [23]:
dataframe_final = pd.concat([dataframe_tweets_lula, dataframe_tweets_bolsonaro, dataframe_tweets_ciro], axis = 0)

In [24]:
dataframe_final.head()

,Data_Hora,IdTweet,Tweet,Candidato
0,2022-07-30 23:16:51+00:00,1553520025637625856,"@LulaOficial Exatamente, a verdade contra a su...",Lula
1,2022-07-30 23:16:51+00:00,1553520024891047943,@gleisi @LulaOficial @CamiloSantanaCE @elmanof...,Lula
2,2022-07-30 23:16:49+00:00,1553520017127374848,"O Manifesto do Direito via USP, com 500 mil as...",Lula
3,2022-07-30 23:16:49+00:00,1553520014518620162,@DeputadoFederal @LulaOficial 22🇧🇷🇧🇷🇧🇷🇧🇷🇧🇷🇧🇷,Lula
4,2022-07-30 23:16:49+00:00,1553520014342381569,"@LulaOficial Analisando, o molusco não sai as ...",Lula

In [25]:
dataframe_final['Candidato'].unique()

array(['Lula', 'Bolsonaro', 'Ciro Gomes'], dtype=object)

In [26]:
dataframe_final.to_csv('dataframe_final_candidatos.csv', sep=',', index=False)